---
driver:
  name: docker

platforms:
  - name: instance
    image: rndmh3ro/docker-ubuntu2204-ansible:latest
    command: /usr/lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
